# Generated by Django 4.1.2 on 2023-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
