# Generated by Django 4.1.2 on 2023-03-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
