# Generated by Django 4.1.2 on 2022-11-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Product_categories'},
        ),
    ]
