# Generated by Django 4.1.2 on 2022-11-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_alter_product_category_options'),
        ('product', '0003_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product_category.product_category'),
            preserve_default=False,
        ),
    ]
