# Generated by Django 4.1.2 on 2022-12-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_category'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='product.product'),
        ),
    ]
