# Generated by Django 4.1.2 on 2022-12-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0001_initial'),
        ('recipe', '0002_remove_recipe_product_recipe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='recipe_category.recipe_category'),
            preserve_default=False,
        ),
    ]
