# Generated by Django 4.1.2 on 2023-01-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipe_product_recipeproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeproduct',
            options={'ordering': ('-created',)},
        ),
    ]
