# Generated by Django 4.1.2 on 2022-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/recipe/'),
        ),
        migrations.AddField(
            model_name='recipe_category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/recipe/'),
        ),
    ]
